### ISSUE TITLE
Handle multi-currency orgs

### ISSUE THREAD

**Issue by seanpat09** [SalesforceFoundation/OutboundFundsModuleNPSP#21]
NOTE: This was initially discovered while working on https://github.com/SalesforceFoundation/OutboundFundsNPSP/issues/18, but this issue may extend beyond the GAU Expenditure issue

It appears that OutboundFundsNPSP has some issues when using multi-currency orgs:

- You aren't given the option to set the currency when creating Disbursements, so it defaults to whatever your org is.
- The GAU Expenditure tab won't take currency conversions into account
- Should the GAU Expenditure tab operate using the User's currency, the Disbursement's currency, or the Org's currency?
- Should the Funding Program/Request/Disbursement all be aligned in currency? 

For example:

INTERFUND is an international foundation with a default currency of USD. Aileen is a grants manager that works in London, with GBP as her default currency. Mina is grantee located in France, and her default currency is EUR.

- If Mina has an approved funding request for 1000 EUR, when Aileen goes to create a disbursement, it will be created in the org's default currency, but without doing the currency conversion. Thus a disbursement for 1000 USD will be created.
- When Aileen goes to the GAU Expenditure tab to allocate the disbursement, the component will display using Aileen's default currency, and she will end up allocating 1000 GBP.

**Comment by seanpat09** [comment]
W-8445569

**Comment by kschaefges** [comment]
For further information see the [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V0000024G3iQAE&title=sfdo-outbound-funds-module) on the Trailblazer Community.
